# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'differences.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(0, 0, 801, 401))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("../../../../../Users/KIIT/Downloads/img1.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setAlignment(QtCore.Qt.AlignCenter)
        self.photo.setObjectName("photo")
        self.pic1 = QtWidgets.QPushButton(self.centralwidget)
        self.pic1.setGeometry(QtCore.QRect(10, 410, 341, 131))
        self.pic1.setObjectName("pic1")
        self.pic2 = QtWidgets.QPushButton(self.centralwidget)
        self.pic2.setGeometry(QtCore.QRect(440, 410, 351, 131))
        self.pic2.setObjectName("pic2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pic1.clicked.connect(self.show_image1)
        self.pic2.clicked.connect(self.show_image2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pic1.setText(_translate("MainWindow", "First Picture"))
        self.pic2.setText(_translate("MainWindow", "Second Picture"))

    def show_image1(self):
        self.photo.setPixmap(QtGui.QPixmap("../../../../../Users/KIIT/Downloads/img1.jpg"))

    def show_image2(self):
        self.photo.setPixmap(QtGui.QPixmap("../../../../../Users/KIIT/Downloads/img2.jpg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
