# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popUpWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spank = QtWidgets.QPushButton(self.centralwidget)
        self.spank.setGeometry(QtCore.QRect(190, 130, 411, 261))
        self.spank.setObjectName("spank")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.spank.clicked.connect(self.show_popUp)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.spank.setText(_translate("MainWindow", "spank me"))

    def show_popUp(self):
        msg = QMessageBox()
        msg.setWindowTitle("Haaaaarder daaaady!!!!!!!")
        msg.setText("AAAH DADDY UR SO BAD AAAAAAAAAAH")
        msg.setIcon(QMessageBox.Critical)
        # msg.setIcon(QMessageBox.Warning)
        # msg.setIcon(QMessageBox.Information)
        # msg.setIcon(QMessageBox.Question)

        # msg.setStandardButtons(QMessageBox.Ok)
        # msg.setStandardButtons(QMessageBox.Open)
        # msg.setStandardButtons(QMessageBox.Save)
        # msg.setStandardButtons(QMessageBox.Cancel)
        # msg.setStandardButtons(QMessageBox.Close)
        # msg.setStandardButtons(QMessageBox.Yes)
        # msg.setStandardButtons(QMessageBox.No)
        # msg.setStandardButtons(QMessageBox.Abort)
        msg.setStandardButtons(QMessageBox.Retry|QMessageBox.Ignore|QMessageBox.Abort)
        # msg.setStandardButtons(QMessageBox.Ignore)

        msg.setDefaultButton(QMessageBox.Abort)

        msg.setInformativeText("give it to me daddy...hmmmmahh")

        msg.setDetailedText("fuck me daddy")

        msg.buttonClicked.connect(self.popUpButton)

        msg.exec_()

    def popUpButton(self, btn_clicked):
        print(btn_clicked.text())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
